# Generated by Django 5.0.6 on 2026-07-19 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('arxiv_search', 'arXiv search'), ('semantic_scholar', 'Semantic Scholar search'), ('openalex', 'OpenAlex search'), ('doi_batch', 'DOI list'), ('pdf_upload', 'PDF upload')], max_length=40)),
                ('query_text', models.CharField(max_length=400)),
                ('max_results', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('papers_added', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('arxiv', 'arXiv'), ('semantic_scholar', 'Semantic Scholar'), ('openalex', 'OpenAlex'), ('crossref', 'Crossref'), ('materials_project', 'Materials Project'), ('manual', 'Manual upload')], default='manual', max_length=40)),
                ('source_id', models.CharField(blank=True, help_text='arXiv ID, DOI, MP ID', max_length=200)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=200)),
                ('title', models.CharField(max_length=600)),
                ('authors', models.TextField(blank=True, help_text='Newline-separated list of authors')),
                ('abstract', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True, help_text='Extracted plain text')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=300)),
                ('pdf_url', models.URLField(blank=True, max_length=1000)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('domains', models.JSONField(blank=True, default=list, help_text='battery, alloy, polymer, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending ingestion'), ('fetched', 'Fetched'), ('parsed', 'Parsed'), ('extracted', 'Entities extracted'), ('indexed', 'Vector-indexed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ingestion_error', models.TextField(blank=True)),
                ('raw_pdf', models.FileField(blank=True, null=True, upload_to='papers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(blank=True, help_text='intro/methods/results/etc.', max_length=120)),
                ('vector_id', models.CharField(blank=True, help_text='ChromaDB chunk id', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='papers.paper')),
            ],
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['source', 'source_id'], name='papers_pape_source_f52884_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['status'], name='papers_pape_status_fa0e02_idx'),
        ),
        migrations.AddIndex(
            model_name='paperchunk',
            index=models.Index(fields=['paper', 'chunk_index'], name='papers_pape_paper_i_e60b6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paperchunk',
            unique_together={('paper', 'chunk_index')},
        ),
    ]
