# Generated by Django 5.0.6 on 2026-07-19 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('materials_project', 'Materials Project'), ('manual', 'Manual'), ('extracted', 'Extracted from paper')], default='manual', max_length=40)),
                ('source_id', models.CharField(blank=True, help_text='MP ID e.g. mp-1101', max_length=100)),
                ('formula', models.CharField(db_index=True, max_length=200)),
                ('formula_pretty', models.CharField(blank=True, max_length=200)),
                ('elements', models.JSONField(blank=True, default=list)),
                ('structure', models.JSONField(blank=True, default=dict, help_text='Crystal structure dict')),
                ('band_gap', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, help_text='g/cm^3', null=True)),
                ('formation_energy_per_atom', models.FloatField(blank=True, help_text='eV/atom', null=True)),
                ('bulk_modulus', models.FloatField(blank=True, help_text='GPa', null=True)),
                ('shear_modulus', models.FloatField(blank=True, help_text='GPa', null=True)),
                ('is_stable', models.BooleanField(default=False)),
                ('theoretical_capacity', models.FloatField(blank=True, help_text='mAh/g', null=True)),
                ('average_voltage', models.FloatField(blank=True, help_text='V', null=True)),
                ('energy_density', models.FloatField(blank=True, help_text='Wh/kg', null=True)),
                ('notes', models.TextField(blank=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['formula'],
                'indexes': [models.Index(fields=['formula'], name='materials_m_formula_4b719e_idx'), models.Index(fields=['source', 'source_id'], name='materials_m_source_980034_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
