# Generated by Django 5.0.6 on 2026-07-19 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('entity_type', models.CharField(choices=[('MATERIAL', 'Material'), ('PROPERTY', 'Property'), ('SYNTHESIS_METHOD', 'Synthesis method'), ('PROCESS_PARAMETER', 'Process parameter'), ('TEMPERATURE', 'Temperature'), ('APPLICATION', 'Application'), ('EQUIPMENT', 'Equipment'), ('MEASUREMENT', 'Measurement technique'), ('CHEMICAL_FORMULA', 'Chemical formula'), ('METRIC', 'Metric / value')], max_length=40)),
                ('normalized', models.CharField(blank=True, help_text='Canonical form, e.g. LiFePO4', max_length=400)),
                ('start_char', models.IntegerField(default=0)),
                ('end_char', models.IntegerField(default=0)),
                ('confidence', models.FloatField(default=0.0)),
                ('extractor', models.CharField(default='regex', help_text='regex/spacy/matscibert/llm', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='papers.paper')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extractor_name', models.CharField(max_length=80)),
                ('entities_found', models.PositiveIntegerField(default=0)),
                ('relations_found', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('success', models.BooleanField(default=False)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='papers.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('HAS_PROPERTY', 'has property'), ('SYNTHESIZED_BY', 'synthesized by'), ('USED_IN', 'used in'), ('MEASURED_BY', 'measured by'), ('REACTS_WITH', 'reacts with'), ('DOPED_WITH', 'doped with'), ('SUBSTITUTE_FOR', 'substitute for'), ('IMPROVES', 'improves'), ('DEGRADES', 'degrades')], max_length=40)),
                ('confidence', models.FloatField(default=0.0)),
                ('evidence', models.TextField(blank=True, help_text='Sentence the relation was extracted from')),
                ('extractor', models.CharField(default='regex', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='extraction.entity')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='papers.paper')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='extraction.entity')),
            ],
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['paper', 'entity_type'], name='extraction__paper_i_27b86d_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entity_type', 'normalized'], name='extraction__entity__8360d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('subject', 'obj', 'relation_type', 'paper')},
        ),
    ]
