# Generated by Django 5.0.6 on 2026-07-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_count', models.PositiveIntegerField(default=0)),
                ('edge_count', models.PositiveIntegerField(default=0)),
                ('graph_json', models.JSONField(default=dict, help_text='NetworkX-format graph dict')),
                ('triggered_by', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('formula', models.CharField(blank=True, max_length=200)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('domain', models.CharField(default='battery', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Aggregated properties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentioned_in', models.ManyToManyField(blank=True, related_name='materials', to='papers.paper')),
            ],
        ),
    ]
